### ISSUE TITLE
[Feature]plist file switching

### ISSUE THREAD

**Issue by shinriyo** [stefandevo/flutter-flavor#6]
Hello.
I didn't try the plugin yet. But, I think to try using it. Because, modify Xcode project is troublesome.

Does it change `GoogleService-Info.plist` file for Firebase?

`ios/Runner/Info.plist` file also.

**Comment by stefandevo** [comment]
Hi
This plugin takes only care of the flutter part. There is no change to native ios/android files. This should be done in your build process.
