### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by rogueturnip** [stefandevo/flutter-flavor#7]
Thanks for the module.  It's helped a lot with my development.

I was wondering are you planning to update the code to support null safety?  Right now it is listed as a legacy module in flutter.  Not a big issue but thought I'd ask.

**Comment by stefandevo** [comment]
Thanks to @jordandevogelaere this is now resolved; sorry for the long wait; missed the notification.
Version 2.0.0 is available now on pub.dev.
